#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
	config_load modeminfo-mqtt
	config_get ENABLED main enabled 0
	[ "$ENABLED" -ne 1 ] && return 0

	DEFAULT_HOSTNAME=$(uci -q get system.@system[0].hostname)

	config_get TIMEOUT main timeout 60
	config_get DISCOVERY main discovery 0
	config_get SERVER  main server  localhost
	config_get PORT    main port    1883
	config_get LOGIN   main login   mqtt
	config_get PASS    main pass
	config_get HOSTNAME main hostname "$DEFAULT_HOSTNAME"

	procd_open_instance
	procd_set_param command /usr/bin/modeminfo-mqtt \
		--discovery "$DISCOVERY" \
		--server "$SERVER" \
		--port "$PORT" \
		--login "$LOGIN" \
		--pass "$PASS" \
		--hostname "$HOSTNAME"
	procd_set_param respawn 10 "$TIMEOUT" 0
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "modeminfo-mqtt"
}

reload_service() {
    /etc/init.d/modeminfo-mqtt stop
    /etc/init.d/modeminfo-mqtt start
}
